# Configuration for the ackermann_steering_controller.
ackermann_steering_controller:
    type: 'ackermann_steering_controller/AckermannSteeringController'

    # Odometry related 
    publish_rate: 50                   # default: 1.0
    open_loop: true

    # Joints
    rear_wheel: 'rear_wheel_joint'
    front_steer: 'steering_wheel_joint'

    # Geometry
    wheel_separation_h: 0.64857 #0.60986
    wheel_radius: 1.6459e-01 #0.1

    # Odometry calibration and tuning
    wheel_separation_h_multiplier: 1.0  # default: 1.0
    wheel_radius_multiplier: 1.0        # default: 1.0
    steer_pos_multiplier: 1.0           # default: 1.0

    # Odometry covariances for the encoder output of the robot.
    # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    pose_covariance_diagonal: [0.001, 0.001, 01000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

    # Top level frame (link) of the robot description
    base_frame_id: 'base_link'

    # Transform from odom -> base_link
    enable_odom_tf: true
    odom_frame_id: 'real_odom'

    # Set to false if the motor driver provides velocity data. 
    estimate_velocity_from_position: true

    # Commands
    publish_cmd: true
    allow_multiple_cmd_vel_publishers: true

    # Velocity and acceleration limits for the robot
    linear:
        x:
            has_velocity_limits    : true
            max_velocity           : 1.0   # m/s
            has_acceleration_limits: true
            max_acceleration       : 0.5    # m/s^2
    angular:
        z:
            has_velocity_limits    : true
            max_velocity           : 3.0   # rad/s
            has_acceleration_limits: true
            max_acceleration       : 3.0    # rad/s^2

    # Other (undocumented but in source code)
    # velocity_rolling_window_size: 10
    # cmd_vel_timeout: 0.5
